apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service
            - name: ORDER_SERVICE_URL
              value: http://order-service
            - name: PAYMENT_SERVICE_URL
              value: http://payment-service
            - name: DELIVERY_SERVICE_URL
              value: http://delivery-service
            - name: EXCHANGE_SERVICE_URL
              value: http://exchange-service
            - name: FILE_SERVICE_URL
              value: http://file-service
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service
            - name: CHAT_SERVICE_URL
              value: http://chat-service
            - name: SPA_URL
              value: http://bookshop-ui
          volumeMounts:
            - name: edge-config-volume
              mountPath: /workspace/config
      volumes:
        - name: edge-config-volume
          configMap:
            name: edge-config
